#!/usr/bin/env python3
"""E2: the enhanced port's scenery, recoloured from YOUR snapshot at build time.

    python3 tools/mkassets.py        (writes build/assets/; make assets)

Nothing here is Imagine's: the rules below are colour choices. The pictures are
Ivan Horn's 16x16 map cells, read from the player's own snapshot and recoloured by
those rules, and they stay in build/.

  build/assets/cells_bankN.bin   every cell of world bank N's cell table (116, or 131
                                 in bank 7), 256 bytes each: 8-bit Layer 2 palette
                                 indices, lines top to bottom
  build/assets/pal_worldN.bin    world N's Layer 2 palette: 256 entries of two bytes
                                 as NextReg $44 takes them (RRRGGGBB, then the low
                                 blue bit); palettes.bin holds all seven in order
  build/assets/assets.asm        what the Next build needs to know (sizes, pages)

THE RECOLOURING RULE. A cell is one bit a pixel. Paper becomes the world's paper
colour (index PAPER); ink becomes one of three tones: HIGHLIGHT where paper lies
directly above or to the left inside the cell (light from the top left), SHADOW
where paper lies directly below or to the right (and not highlighted), INK
otherwise. Edges of the cell count as ink, so cells tile without seams.

Colours avoid the two values the Next treats as transparent here: RGB332 $00 (the
ULA's black is made transparent in E2, so its sprites show over Layer 2) and $E3
(the Next's default transparent colour).
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from specfile import Z80Snapshot  # noqa: E402
import render_world as rw          # noqa: E402

OUT = "build/assets"
ART = "build/art"                   # tools/artimport.py's checked hand-made cells, if any
PAPER, INK, HIGHLIGHT, SHADOW = 16, 17, 18, 19
ART_FIRST = 20                      # hand-made colours take the palette from here

# World colours, 3 bits each of red, green, blue: paper, ink, highlight, shadow.
# A starting point from the art bible's world moods; the hand-made art replaces them.
RULES = {
    1: ((0, 1, 0), (2, 5, 1), (4, 7, 2), (1, 3, 0)),   # Forest
    2: ((1, 1, 0), (5, 4, 1), (7, 6, 3), (3, 2, 0)),   # Cavern
    3: ((0, 1, 3), (5, 6, 7), (7, 7, 7), (3, 4, 6)),   # Sky
    4: ((1, 1, 1), (3, 5, 4), (5, 7, 6), (2, 3, 2)),   # Labyrinth
    5: ((0, 1, 2), (1, 5, 4), (3, 7, 6), (0, 3, 3)),   # Sea
    6: ((1, 0, 0), (6, 2, 0), (7, 5, 1), (3, 1, 0)),   # Hell
    7: ((1, 1, 2), (5, 6, 7), (7, 7, 7), (3, 4, 5)),   # The Last World
}
BANK_OF_WORLD = {1: 3, 2: 3, 3: 4, 4: 4, 5: 6, 6: 6, 7: 7}
CELL_PAGE0 = 64                     # 8K pages 64-79 (16K banks 32-39) hold the cell sheets


def rgb332(c):
    r, g, b = c
    return r << 5 | g << 2 | b >> 1


def nextreg44(c):
    r, g, b = c
    return bytes([r << 5 | g << 2 | b >> 1, b & 1])


def recolour(bits):
    """bits: 16 rows of 16-bit ints (bit 15 leftmost). Returns 256 palette indices."""
    def ink(x, y):
        if not (0 <= x < 16 and 0 <= y < 16):
            return True
        return bits[y] >> (15 - x) & 1
    out = bytearray()
    for y in range(16):
        for x in range(16):
            if not ink(x, y):
                out.append(PAPER)
            elif not ink(x, y - 1) or not ink(x - 1, y):
                out.append(HIGHLIGHT)
            elif not ink(x, y + 1) or not ink(x + 1, y):
                out.append(SHADOW)
            else:
                out.append(INK)
    return bytes(out)


def hand_made(bank):
    """The bank's hand-made cells: {place: [256 indices]}, and the colours they use."""
    path = f"{ART}/cells_bank{bank}.json"
    if os.environ.get("NOART") or not os.path.exists(path):
        return {}, []
    art = json.load(open(path))
    return {int(k): v for k, v in art["cells"].items()}, [tuple(c) for c in art["colours"]]


def main():
    os.makedirs(OUT, exist_ok=True)
    snap = Z80Snapshot(open("data/athena128.z80", "rb").read())
    for world, colours in RULES.items():
        for c in colours:
            if rgb332(c) in (0x00, 0xE3):
                sys.exit(f"world {world}: colour {c} is transparent on the Next")
    lines = ["; Generated by tools/mkassets.py from the player's own snapshot. Not committed.",
             f"CELL_PAGE0 EQU {CELL_PAGE0}"]
    art_colours = {}
    page = CELL_PAGE0
    done = set()
    palettes = []
    for world in range(1, 8):
        bank = BANK_OF_WORLD[world]
        m = rw.world_memory(snap, world)
        if bank not in done:
            table, end = rw.word(m, 0x7665), rw.word(m, 0x7667)
            count = (end - table) // 32
            cells, colours = hand_made(bank)
            art_colours[bank] = colours
            sheet = bytearray()
            for n in range(count):
                if n in cells:
                    sheet += bytes(ART_FIRST + i for i in cells[n])
                    continue
                src = table + 32 * n
                bits = [m[src + 2 * y] << 8 | m[src + 2 * y + 1] for y in range(16)]
                sheet += recolour(bits)
            open(f"{OUT}/cells_bank{bank}.bin", "wb").write(sheet)
            pages = (len(sheet) + 0x1FFF) // 0x2000
            lines += [f"CELLS_BANK{bank}_PAGE EQU {page}", f"CELLS_BANK{bank}_COUNT EQU {count}"]
            page += pages
            done.add(bank)
        pal = bytearray()
        paper, ink, hi, sh = RULES[world]
        hand = art_colours.get(bank, [])
        for i in range(256):
            if ART_FIRST <= i < ART_FIRST + len(hand):
                pal += nextreg44(hand[i - ART_FIRST])
            else:
                pal += nextreg44({INK: ink, HIGHLIGHT: hi, SHADOW: sh}.get(i, paper))
        open(f"{OUT}/pal_world{world}.bin", "wb").write(pal)
        palettes.append(bytes(pal))
    open(f"{OUT}/palettes.bin", "wb").write(b"".join(palettes))
    lines.append(f"PAL_PAGE EQU {page}")             # the seven palettes, 512 bytes each from world 1
    lines.append(f"ASSET_PAGE_END EQU {page + 1}")
    open(f"{OUT}/assets.asm", "w").write("\n".join(lines) + "\n")
    hand = sum(len(hand_made(b)[0]) for b in sorted(done))
    print(f"mkassets: cell sheets for banks {sorted(done)}, palettes for worlds 1-7, pages "
          f"{CELL_PAGE0}-{page - 1}" + (f"; {hand} hand-made cells" if hand else ""))


if __name__ == "__main__":
    main()
